essaie

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -9,6 +9,8 @@ jobs:
         java-version: [ 24, 25-ea ]
     steps:
       - uses: actions/checkout@v4
+        with:
+            fetch-depth: 0
       - uses: actions/setup-java@v4
         with:
           java-version: ${{ matrix.java-version }}
@@ -39,13 +41,17 @@ jobs:
       - name: Run mutation testing on core module
         if: matrix.java-version == '24'
         run: |
-          cd core
-          mvn clean install -DskipTests
-          mvn org.pitest:pitest-maven:mutationCoverage
+          mvn -B install -DskipTests -pl core -am
+          mvn -B org.pitest:pitest-maven:mutationCoverage -pl core
       - name: Extract mutation score
         if: matrix.java-version == '24'
         id: current_score
         run: |
+          if [ ! -f "core/target/pit-reports/index.html" ]; then
+            echo "::error::index.html not found"
+            exit 1
+          fi
+
           CURRENT_SCORE=$(grep -oP '(?<=<td>)\d+%' core/target/pit-reports/index.html | sed -n '2p' | tr -d '%')
           echo "score=$CURRENT_SCORE" >> $GITHUB_OUTPUT
       - name: Compare with previous score
